cricketadmin/urls.py
from django.urls import path

from . import views

app_name = 'cricketadmin'
urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.result, name='result'),

]

cricketproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cricketadmin.urls')),
    path('teams/', include('teams.urls')),
    path('players/', include('players.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

players/urls.py
from django.urls import path

from . import views

app_name = 'players'
urlpatterns = [
    path('', views.index, name='index'),
    path('playerdetail/<str:player_id>/',views.playerdetail, name='playerdetail'),
    path('createplayer/',views.createplayer, name='createplayer'),
    path('save/', views.save, name='save'),
]

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'
urlpatterns = [
    path('', views.index, name='index'),
    path('teamdetail/<str:team_id>/',views.teamdetail, name='teamdetail'),
    path('createteam/',views.createteam, name='createteam'),
    path('save/', views.save, name='save'),
]

cricketadmin/models.py
from django.db import models


# Create your models here.
class Match(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)

    def __str__ (self):
        return self.name

class Team(models.Model):
    identifier = models.AutoField(primary_key=True)
    teamName = models.CharField(max_length=200)
    logouri = models.ImageField(upload_to='images/')
    club_state = models.CharField(max_length=200)
    players = models.ManyToManyField('Player', related_name='players')
    created_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__ (self):
        return self.teamName

class Player(models.Model):
    identifier = models.AutoField(primary_key=True)
    firstName = models.CharField(max_length=200)
    lastName = models.CharField(max_length=200)
    imageUri = models.ImageField(upload_to='images/')
    player_jersey_number = models.IntegerField()
    country = models.CharField(max_length=200)
    matches = models.ForeignKey(Match, on_delete=models.CASCADE)
    run = models.IntegerField()
    highest_scores = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__ (self):
        return self.firstName


class Winner(models.Model):
    matchdate = models.DateField(auto_now_add=False,null=True, blank=True)
    matches = models.ForeignKey(Match, on_delete=models.CASCADE)
    team_a = models.ForeignKey(Team, on_delete=models.CASCADE,related_name='team_a')
    team_b = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='team_b')
    score_a = models.IntegerField()
    score_b = models.IntegerField()
    winner_team = models.ForeignKey(Team, on_delete=models.CASCADE)

players/models.py
from django.db import models

# Create your models here.

teams/models.py
from django.db import models

# Create your models here.

cricketadmin/views.py
import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db.models import Q


import random

from cricketadmin.models import Player, Team, Match, Winner


def index(request):
    teamobj = Team.objects.all()
    return render(request, 'cricketadmin/index.html', {'teamobj': teamobj})


def result(request):
    teamobj = Team.objects.all()
    winnerobj = Winner.objects.all()
    matches = Match.objects.all()
    randomMatch = random.choice(matches)
    print(randomMatch)
    state = request.POST.get('club_state')
    print(state)
    if state == "State Level":
        teams = Team.objects.filter(Q(club_state="State Level"))
        # print(teams)
        # teamchoice = random.choices(teams, k=2)
        # print(teamchoice)
        team_a = random.choice(teams)
        print(team_a)
        team_b = random.choice(teams)
        print(team_b)
    elif state == "National Level":
        teams = Team.objects.filter(Q(club_state="National Level"))
        # print(teams)
        # teamchoice = random.choices(teams, k=2)
        # # print(teamchoice)
        team_a = random.choice(teams)
        print(team_a)
        team_b = random.choice(teams)
        print(team_b)
    else:
        teams = Team.objects.filter(Q(club_state="International Level"))
        # print(teams)
        # teamchoice = random.choices(teams, k=2)
        # print(teamchoice)
        team_a = random.choice(teams)
        print(team_a)
        team_b = random.choice(teams)
        print(team_b)

    start_date = datetime.date(2021, 1, 1)
    end_date = datetime.date(2025, 1, 1)

    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + datetime.timedelta(days=random_number_of_days)
    # print(random_date)
    score_a = random.randint(10,1000)
    print(score_a)
    score_b = random.randint(10,1000)
    print(score_b)
    if score_a > score_b:
        winner_team = team_a
    else:
        winner_team = team_b
    return render(request, 'cricketadmin/result.html', {'state':state, 'winnerobj': winnerobj, 'randomMatch':randomMatch,'team_a':team_a,'team_b':team_b,'random_date':random_date, 'score_a':score_a,'score_b':score_b,'winner_team':winner_team})

players/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from cricketadmin.models import Team, Match, Player


def index(request):
    name_list = Player.objects.order_by('-created_date')
    # print(name_list)
    return render(request, 'players/index.html', {'name_list': name_list})

def playerdetail(request, player_id):
    players = Player.objects.get(identifier=player_id)
    return render(request, 'players/playerdetail.html', {'p': players})

def createplayer(request):
    matches = Match.objects.all()
    teams = Team.objects.all()
    return render(request, 'players/createplayer.html', {'matches':matches, 'teams':teams})

def save(request):
    matchObj = Match.objects.get(id=request.POST.get('matches'))
    Player.objects.create(firstName=request.POST.get('firstName'), lastName=request.POST.get('lastName'), imageUri=request.FILES['imageUri'], player_jersey_number=request.POST.get('player_jersey_number'),country=request.POST.get('country'),matches=matchObj,run=request.POST.get('run'),highest_scores=request.POST.get('highest_scores'))
    return HttpResponseRedirect('/players')

teams/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from cricketadmin.models import Team, Match, Player


def index(request):
    name_list = Team.objects.order_by('-created_date')
    return render(request, 'teams/index.html', {'name_list':name_list})

def teamdetail(request,team_id):
    team = Team.objects.get(identifier=team_id)
    players = team.players.all()
    # print(players)
    return render(request, 'teams/teamdetail.html', {'t': team,'players':players})

def createteam(request):
    players = Player.objects.all()
    return render(request, 'teams/createteam.html', {'players':players})

def save(request):
    playerlist = request.POST.getlist('players')
    result = []
    for p in playerlist:
         playerObj = Player.objects.get(identifier=p)
         # print(playerObj)
         result.append(playerObj)

    # print(result)
    # print(playerObjs)
    team = Team.objects.create(teamName=request.POST.get('teamName'), logouri=request.FILES['logouri'], club_state=request.POST.get('club_state'))
    team.players.add(*result)
    return HttpResponseRedirect('/teams')

cricketadmin/templates/cricketadmin/index.html
<style>
.block{
font-size:20px;
}
</style>

<div style="text-align:center; font-size:25px">
  <h3>Matches Fixtures</h3><br><br>
</div>

<form action="{% url 'cricketadmin:result' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
    <div class="block">
     <div style="text-align:center">
    <label>Tournament Draw:   </label>
    <select name="club_state" id="club_state" style="height:50px; font-size:18px">
        <option disabled selected value>   -- select an option -- </option>
        <option value="State Level">  State Championship</option>
        <option value="National Level"> National Championship</option>
        <option value="International Level">International Championship</option>
    </select><br><br>
    <input type="submit" value="Draw" style="font-size:20px"><br><br>
    </div>
    </div>

</form>

cricketadmin/templates/cricketadmin/result.html
<style>

table, th, td {
  margin: auto;
  style: align:center;
  border: 1px solid black;
  border-collapse: collapse;
  outline:1px solid black;
}
th, td {
  padding: 15px;
  text-align:center;
}
th{
height: 90px;
font-size:20px;
color:blue
}
.border{
padding:15px;
border: 1px solid sienna;
outline:1px dotted sienna;
}
.paging_style{
text-align:center;
font-size: 18px;
}
</style>

<div style="text-align:center; font-size:25px">
  <h3>Matches Fixtures</h3><br>
</div>

<form method="GET">
  {% csrf_token %}
    <div style="text-align:center">
    <h2>Result for {{state}} Championship</h2><br>
      <div class="table">
           <table class="table">
               <tr>
                   <th>Date</th>
                   <th>Match</th>
                   <th>Team A</th>
                   <th>Team B</th>
                   <th>Score of Team A</th>
                   <th>Score of Team B</th>
                   <th>Winner of the Match</th>
               </tr>
                  <tr>
                      <td><h4>{{random_date}}</h4></td>
                      <td><h4>{{randomMatch}}</h4></td>
                      <td><h4>{{team_a}}</h4></td>
                      <td><h4>{{team_b}}</h4></td>
                      <td><h4>{{score_a}}</h4></td>
                      <td><h4>{{score_b}}</h4></td>
                      <td><h4>{{winner_team}}</h4></td>
                  </tr>
             </table><br><br>
      </div>
        <a href="{% url 'cricketadmin:index' %}" style="font-size: 20px;">Draw Again</a>
    </div>

</form>

players/templates/players/createplayer.html
<div style="text-align:center">
  <h1>Create Player</h1>
</div>

<form action="{% url 'players:save' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <label for="firstName">First Name: </label>
  <input type="text" id="firstName" name="firstName"><br><br>
  <label for="lastName">Last Name: </label>
  <input type="text" id="lastName" name="lastName"><br><br>
  <label for="imageUri">Profile Pic: </label>
  <input type="file" id="imageUri" name="imageUri"><br><br>
  <label for="player_jersey_number">Player Jersey Number: </label>
  <input type="text" id="player_jersey_number" name="player_jersey_number"><br><br>
  <label for="country">Country: </label>
   <select name="country" id="country" style="height:30px;">
        <option disabled selected value> -- select an option -- </option>
        <option value="Afghanistan">Afghanistan</option>
        <option value="Albania">Albania</option>
        <option value="Algeria">Algeria</option>
        <option value="Andorra">Andorra</option>
        <option value="Angola">Angola</option>
        <option value="Antigua and Barbuda">Antigua and Barbuda</option>
       <option value="Argentina">Argentina</option>
        <option value="Armenia">Armenia</option>
        <option value="Australia">Australia</option>
        <option value="Austria">Austria</option>
        <option value="Azerbaijan">Azerbaijan</option>
        <option value="Bahamas">Bahamas</option>
       <option value="Bahrain">Bahrain</option>
        <option value="Bangladesh">Bangladesh</option>
        <option value="Barbados">Barbados</option>
        <option value="Belarus">Belarus</option>
        <option value="Belgium">Belgium</option>
        <option value="Belize">Belize</option>
       <option value="Benin">Benin</option>
        <option value="Bhutan">Bhutan</option>
        <option value="Brazil">Brazil</option>
        <option value="Bulgaria">Bulgaria</option>
        <option value="Canada">Canada</option>
        <option value="China">China</option>
       <option value="Colombia">Colombia</option>
        <option value="Costa Rica">Costa Rica</option>
        <option value="Denmark">Denmark</option>
        <option value="Egypt">Egypt</option>
        <option value="Estonia">Estonia</option>
        <option value="Ethiopia">Ethiopia</option>
       <option value="Faroe Islands">Faroe Islands</option>
        <option value="France">France</option>
        <option value="Georgia">Georgia</option>
        <option value="Germany">Germany</option>
        <option value="Greece">Greece</option>
        <option value="India">India</option>
       <option value="Italy">Italy</option>
        <option value="Japan">Japan</option>
        <option value="Malaysia">Malaysia</option>
        <option value="Singapore">Singapore</option>
        <option value="Thailand">Thailand</option>
        <option value="United Kingdom">United Kingdom</option>
        <option value="United States of America">United States of America</option>
        <option value="Zimbabwe">Zimbabwe</option>
     </select><br><br>
  <label for="matches">Matches: </label>
    <select name="matches" id="matches" style="height:30px;">
        <option disabled selected value> -- select an option -- </option>
        {% for match in matches %}
           <option value="{{ match.id }}" >{{ match.name }}</option>
        {% endfor %}
    </select><br><br>
   <label for="run">Run: </label>
   <input type="text" id="run" name="run"><br><br>
    <label for="highest_scores">Highest Scores: </label>
   <input type="text" id="highest_scores" name="highest_scores"><br><br>
<!--    <label for="team">Team: </label>-->
<!--    <select name="team" id="team" style="height:30px;">-->
<!--        <option disabled selected value> &#45;&#45; select an option &#45;&#45; </option>-->
<!--        {% for team in teams %}-->
<!--           <option value="{{ team.identifier }}" >{{ team.teamName }}</option>-->
<!--        {% endfor %}-->
<!--    </select>-->
    <br><br><br>
    <input type="submit" value="Create">
</form>

<a href="{% url 'teams:index' %}">Back</a>

players/templates/players/index.html
<h3>Players Name</h3>

{% if name_list %}
<ul>
  {% for n in name_list %}
    <li>
      <a href="{% url 'players:playerdetail' n.identifier %}">{{ n.firstName }}  {{ n.lastName }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>No Players are available.</p>
{% endif %}

<a href="{% url 'players:createplayer' %}">Create Player</a>

players/templates/players/playerdetail.html
<div style="text-align: center">
<h1>Player Detail Information</h1>
</div>


       <img align="right" src="/media/{{p.imageUri}}" style="width:200px;height:200px"><br><br>
       <label><b>First Name: </b></label>{{p.firstName}}<br><br>
       <label><b>Last Name: </b></label>{{p.lastName}}<br><br>
<!--       <div style="text-align:right"><label><b>Profile Pic: </b></label></div>-->
       <label><b>Player Jersey Number:  </b></label>{{p.player_jersey_number}}<br><br>
       <label><b>Country: </b></label>{{p.country}}<br><br>
       <label><b>Matches: </b></label>{{p.matches}}<br><br>
       <label><b>Run: </b></label>{{p.run}}<br><br>
       <label><b>Highest Scores: </b></label>{{p.highest_scores}}<br><br><br>


<a href="{% url 'teams:index'  %}">Back to Team List Page</a><br><br>

<a href="{% url 'players:index' %}">Back to Player List Page</a>

teams/templates/teams/createteam.html
<div style="text-align:center">
  <h1>Create Team</h1>
</div>

<form action="{% url 'teams:save' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <label for="teamName">Team Name: </label>
  <input type="text" id="teamName" name="teamName"><br><br>
  <label for="logouri">Logo: </label>
  <input type="file" id="logouri" name="logouri"><br><br>
  <label for="club_state">Club State: </label>
  <input type="text" id="club_state" name="club_state"><br><br>
    <label for="players" id="result">Players: </label>
   <select name="players" id="players" multiple>
<!--        <option disabled selected value> &#45;&#45; select an option &#45;&#45; </option>-->
        {% for player in players %}
           <option value="{{ player.identifier }}" >{{ player.firstName }} {{ player.lastName }}</option>
        {% endfor %}
    </select><br><br><br>
    <input type="submit" value="Create">
</form>

<a href="{% url 'teams:index' %}">Back</a><br><br>
<a href="{% url 'players:createplayer' %}">Create Player</a>

teams/templates/teams/index.html
<h3>Teams Name</h3>

{% if name_list %}
<ul>
  {% for n in name_list %}
    <li>
      <a href="{% url 'teams:teamdetail' n.identifier %}">{{ n.teamName }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>No Teams are available.</p>
{% endif %}

<a href="{% url 'teams:createteam' %}">Create Team</a>

teams/templates/teams/teamdetail.html
<div style="text-align: center">
<h1>Team Detail Information</h1>
</div>

       <img align="right" src="/media/{{t.logouri}}" style="width:200px;height:200px"><br><br>
       <label><b>Team Name: </b></label>{{t.teamName}}<br><br>
<!--       <div style="text-align:right"><label><b>Profile Pic: </b></label></div>-->
       <label><b>Club State:  </b></label>{{t.club_state}}<br><br>
       <label><b>Players: </b></label><br><br>
              {% for player in t.players.all %}
                   <li><a href="{% url 'players:playerdetail' player.identifier %}">{{player.firstName}} {{player.lastName}}</a></li>
              {% endfor %}<br><br>

<a href="{% url 'teams:index' %}">Back</a>